-- 物品配置数据
return {
    ["鸡肉"] = { name = "鸡肉", type = "consumable", desc = "普通的鸡肉，可以恢复少量生命", effect = "heal", value = 10, price_buy = 5, price_sell = 2 },
    ["兔肉"] = { name = "兔肉", type = "consumable", desc = "新鲜的兔肉，食用可恢复生命", effect = "heal", value = 8, price_buy = 4, price_sell = 1 },
    ["鸡毛"] = { name = "鸡毛", type = "material", desc = "普通的鸡毛，或许有些用处", effect = "none", value = 0, price_buy = 0, price_sell = 1 },
    ["兔皮"] = { name = "兔皮", type = "material", desc = "柔软的兔皮，可用于制作护具", effect = "none", value = 0, price_buy = 0, price_sell = 3 },
    ["狐狸皮"] = { name = "狐狸皮", type = "material", desc = "品质上佳的狐皮，做衣服很暖和", effect = "none", value = 0, price_buy = 0, price_sell = 15 },
    ["灵狐内丹"] = { name = "灵狐内丹", type = "material", desc = "灵狐体内的内丹，蕴含灵力", effect = "none", value = 0, price_buy = 0, price_sell = 50 },
    ["蛇胆"] = { name = "蛇胆", type = "material", desc = "毒蛇的胆，是炼丹的好材料", effect = "none", value = 0, price_buy = 0, price_sell = 10 },
    ["蛇皮"] = { name = "蛇皮", type = "material", desc = "坚韧的蛇皮，可用于炼器", effect = "none", value = 0, price_buy = 0, price_sell = 8 },
    ["解毒草"] = { name = "解毒草", type = "consumable", desc = "能解百毒的草药", effect = "heal", value = 15, price_buy = 10, price_sell = 4 },
    ["水灵珠"] = { name = "水灵珠", type = "material", desc = "蕴含水之灵力的珠子，修炼用品", effect = "none", value = 0, price_buy = 0, price_sell = 30 },
    ["狼皮"] = { name = "狼皮", type = "material", desc = "厚实的狼皮，防御材料", effect = "none", value = 0, price_buy = 0, price_sell = 12 },
    ["狼牙"] = { name = "狼牙", type = "material", desc = "锋利的狼牙，可制作武器", effect = "none", value = 0, price_buy = 0, price_sell = 8 },
    ["灵石碎片"] = { name = "灵石碎片", type = "material", desc = "碎裂的灵石，仍有微弱灵力", effect = "none", value = 0, price_buy = 0, price_sell = 20 },
    ["铁矿石"] = { name = "铁矿石", type = "material", desc = "普通的铁矿石，炼器基础材料", effect = "none", value = 0, price_buy = 15, price_sell = 6 },
    ["小回血丹"] = { name = "小回血丹", type = "consumable", desc = "最基础的丹药，恢复少量生命", effect = "heal", value = 30, price_buy = 20, price_sell = 8 },
    ["中回血丹"] = { name = "中回血丹", type = "consumable", desc = "品质不错的丹药，恢复中等生命", effect = "heal", value = 80, price_buy = 60, price_sell = 25 },
    ["大回血丹"] = { name = "大回血丹", type = "consumable", desc = "上品丹药，恢复大量生命", effect = "heal", value = 200, price_buy = 150, price_sell = 60 },
    ["聚灵丹"] = { name = "聚灵丹", type = "consumable", desc = "服用后短时间内修炼速度翻倍", effect = "buff", value = 50, price_buy = 100, price_sell = 40 },
    ["灵石"] = { name = "灵石", type = "material", desc = "修仙世界的通用货币，蕴含纯净灵力", effect = "none", value = 0, price_buy = 0, price_sell = 100 },
    ["火灵珠"] = { name = "火灵珠", type = "material", desc = "蕴含火之灵力的珠子", effect = "none", value = 0, price_buy = 0, price_sell = 35 },
    ["雷灵珠"] = { name = "雷灵珠", type = "material", desc = "蕴含雷霆之力的珠子，极为珍贵", effect = "none", value = 0, price_buy = 0, price_sell = 80 },
    ["妖王内丹"] = { name = "妖王内丹", type = "material", desc = "妖王体内的内丹，蕴含强大妖力", effect = "none", value = 0, price_buy = 0, price_sell = 200 },
    ["上品灵石"] = { name = "上品灵石", type = "material", desc = "品质极高的灵石，修炼圣品", effect = "none", value = 0, price_buy = 0, price_sell = 500 },
}
