-- 地图配置数据
return {
    ["新手村"] = {
        name = "新手村",
        desc = "灵气稀薄的小村庄，修仙之路从这里开始",
        monsters = "野鸡,野兔",
        npcs = "村长老李,杂货商王二",
        front = "青云山脚",
        back = "",
        left = "灵溪边",
        right = "荒野小径",
        level_req = 0,
    },
    ["青云山脚"] = {
        name = "青云山脚",
        desc = "青云宗山门所在，灵气渐浓，隐有仙鹤飞过",
        monsters = "灵狐,毒蛇",
        npcs = "守山弟子张三,丹药商刘掌柜",
        front = "青云山腰",
        back = "新手村",
        left = "幽暗密林",
        right = "落日峡谷",
        level_req = 3,
    },
    ["灵溪边"] = {
        name = "灵溪边",
        desc = "清澈的灵溪潺潺流过，偶有灵鱼跃出水面",
        monsters = "水灵兽,毒蛙",
        npcs = "钓鱼翁,采药人赵六",
        front = "",
        back = "",
        left = "",
        right = "新手村",
        level_req = 1,
    },
    ["荒野小径"] = {
        name = "荒野小径",
        desc = "荒凉的小路，杂草丛生，偶有妖兽出没",
        monsters = "荒原狼,石头怪",
        npcs = "流浪商人",
        front = "",
        back = "",
        left = "新手村",
        right = "黑风洞口",
        level_req = 2,
    },
    ["青云山腰"] = {
        name = "青云山腰",
        desc = "半山之上，云雾缭绕，灵气充裕",
        monsters = "云雾兽,山魈",
        npcs = "青云长老,炼器师陈铁",
        front = "青云山顶",
        back = "青云山脚",
        left = "",
        right = "",
        level_req = 6,
    },
    ["青云山顶"] = {
        name = "青云山顶",
        desc = "山巅之上，俯瞰天下，此处灵气最为浓郁",
        monsters = "天鹰,雷兽",
        npcs = "掌门玄清真人",
        front = "",
        back = "青云山腰",
        left = "",
        right = "",
        level_req = 10,
    },
    ["幽暗密林"] = {
        name = "幽暗密林",
        desc = "古木参天，光线昏暗，深处隐藏着危险",
        monsters = "树妖,暗影蛇,食人花",
        npcs = "神秘猎人",
        front = "",
        back = "",
        left = "",
        right = "青云山脚",
        level_req = 5,
    },
    ["落日峡谷"] = {
        name = "落日峡谷",
        desc = "夕阳染红的峡谷，火属性灵气充沛",
        monsters = "火蜥蜴,岩浆兽",
        npcs = "铸剑师欧冶",
        front = "",
        back = "",
        left = "青云山脚",
        right = "",
        level_req = 5,
    },
    ["黑风洞口"] = {
        name = "黑风洞口",
        desc = "阴风阵阵的洞穴入口，传来阵阵妖气",
        monsters = "蝙蝠精,洞穴蜘蛛,黑风妖",
        npcs = "",
        front = "",
        back = "",
        left = "荒野小径",
        right = "",
        level_req = 8,
    },
}
